### ISSUE TITLE
Factory example and worker settings

### ISSUE THREAD

**Issue by asmodehn** [Robpol86/Flask-Celery-Helper#14]
In the factory example, there is no instructions on how to run the worker...
Since the BROKER_URL and RESULT_BACKEND are set dynamically I wonder how the worker can get these settings...

if you run
```
celery -A example.celery worker
```

The settings in the worker will be different than in the app...
Just raising this issue since i m having trouble setting this over multiple machines...

**Comment by Robpol86** [comment]
https://github.com/Robpol86/Flask-Celery-Helper/issues/10
