### ISSUE TITLE
Did you remember to import the module containing this task?

### ISSUE THREAD

**Issue by rlam3** [Robpol86/Flask-Celery-Helper#16]
Did you remember to import the module containing this task?
Or maybe you are using relative imports?
Please see http://bit.ly/gLye1c for more information.

What does this mean?

I followed your extensions guide... but not sure  why this is happening.

How do I start my celery task worker ? 

````
/extensions.py # from celery import Celery; celery = Celery()
/app.py # etc... from extensions import celery; celery.init_app(app) inside app; app.register_blueprints etc...
/tasks
  /celery_worker.py # from extensions import celery
  /email.py # from celery_worker import celery; @celery.task def add(x,y): return x+y
````

Because I'm using the factory way of creating apps. how do you create the celery worker this way?

Also how will i be able to use flask celery-helper in conjuction with @periodc from celery to schedule periodic tasks?

**Comment by Robpol86** [comment]
I don't feel comfortable clicking url shortened links. Why didn't you just include your output in this GitHub issue?

I don't know how to help you. Try starting from https://github.com/Robpol86/Flask-Large-Application-Example/ and add your code to it slowly until it breaks.
