### ISSUE TITLE
CELERY_IMPORTS - documentation on this? 

### ISSUE THREAD

**Issue by vincentwhales** [Robpol86/Flask-Celery-Helper#18]
Hi I can't seem to find where the variable 'CELERY_IMPORTS' is defined in your source. 

I would like to learn more about what it does because I've been running errors with setting the right value with this and I was only able to get my app working via brute forcing values for this variable.

**Comment by fkztw** [comment]
It's used by `Celery` not `Flask-Celery-Helper`
FYI: https://github.com/celery/celery/search?q=CELERY_IMPORTS&type=Commits
