### ISSUE TITLE
Running Worker as Stated in Docs for Factory Pattern

### ISSUE THREAD

**Issue by justinwp** [Robpol86/Flask-Celery-Helper#7]
How about adding how to run the worker for the factory pattern? I'm running into issues with celery not loading the flask app configs from create_app().

**Comment by Robpol86** [comment]
Not sure I understand. This is how I run the worker in my projects:
https://github.com/Robpol86/Flask-Large-Application-Example/blob/master/manage.py#L234

How are you passing your Flask app config to your celery worker(s)?

**Comment by justinwp** [comment]
Got it working from your example. Simplified version below
```
    app = create_app()
    celery_args = ['celery', 'worker', '-l', 'info']
    with app.app_context():
        return celery_main(celery_args)
```

**Comment by iandennismiller** [comment]
Thanks for this conversation.  I ran into the same problem and justinwp's example finally made it click for me.
