### ISSUE TITLE
Redis and Celery

### ISSUE THREAD

**Issue by harrywang** [Robpol86/Flask-Celery-Helper#9]
Hi, I wonder whether I need to install Redis Helper for this to work. Do I need to start redis first by running src/redis-server first and use celery worker to start a worker? Thanks a lot for your help and this helper too :) I am trying to use your helpers to make Celery work with Flasky example at: http://blog.miguelgrinberg.com/post/using-celery-with-flask and https://github.com/miguelgrinberg/flasky but am having trouble to run celery worker -A app.celery --loglevel=info, which returns this error:

[2015-05-12 16:04:12,581: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 2.00 seconds...

**Comment by Robpol86** [comment]
Yep you need to have Redis already running before starting any celery/flask processes.

**Comment by harrywang** [comment]
@Robpol86 Thanks. I had Redis running. Do I need to start a Celery worker? 

    celery worker -A app.celery --loglevel=info

returns the following error - it is not using Redis I think. Any ideas?

**Comment by Robpol86** [comment]
Not sure, it depends on how you structure your application.
